<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<UserSecretsId>3154785a-1f44-47f7-96fd-0b12363af234</UserSecretsId>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="MediatR" Version="12.4.1" />
		<PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="9.0.2" />
	</ItemGroup>

</Project>